name: update documentation
run-name: update /content and README.md

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  scala:
    uses: leowajda/eureka/.github/workflows/update-table.yml@feature/yaml-migration
    with:
      path-filter: 'src/main/**/*.scala'
    secrets: inherit
